SELECT B.YEAR, ABS(A.SIZE_OF_COLONY-B.MAX_COLONY) AS YEAR_DEV, A.ID
FROM ECOLI_DATA AS A
LEFT JOIN (SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_COLONY
        FROM ECOLI_DATA
        GROUP BY YEAR) AS B
ON YEAR(A.DIFFERENTIATION_DATE)= B.YEAR
ORDER BY YEAR, YEAR_DEV