SELECT C.ID, B.FISH_NAME, A.LENGTH
FROM (SELECT MAX(LENGTH) AS LENGTH, FISH_TYPE
        FROM FISH_INFO
        GROUP BY FISH_TYPE) AS A
JOIN FISH_NAME_INFO AS B
ON A.FISH_TYPE = B.FISH_TYPE
JOIN FISH_INFO AS C
ON C.FISH_TYPE = A.FISH_TYPE AND C.LENGTH = A.LENGTH
ORDER BY C.ID